/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get process and configuration status */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the full normalized configuration */
        get: operations["getConfig"];
        /**
         * Replace the full configuration
         * @description Validates, atomically persists and hot-applies the supplied
         *     configuration. On any failure the previous file and runtime snapshot
         *     remain untouched.
         */
        put: operations["putConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate a configuration without saving or applying it
         * @description Always responds `200` for well-formed requests, even when the
         *     supplied configuration content is invalid; validation problems are
         *     reported in `issues`. `400 invalid_request` is returned only for
         *     malformed JSON.
         */
        post: operations["validateConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List routes
         * @description Returns all configured routes in configuration order.
         */
        get: operations["listRoutes"];
        put?: never;
        /**
         * Create a route
         * @description Adds a route and hot-applies the configuration. A duplicate name or
         *     prefix yields `400 validation_failed`.
         */
        post: operations["createRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route name. */
                name: components["parameters"]["RouteName"];
            };
            cookie?: never;
        };
        /** Get a route */
        get: operations["getRoute"];
        /**
         * Update a route
         * @description Replaces the named route and hot-applies the configuration.
         *     `route.name` must equal the `{name}` path segment, otherwise
         *     `400 validation_failed`.
         */
        put: operations["updateRoute"];
        post?: never;
        /** Delete a route */
        delete: operations["deleteRoute"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{name}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route name. */
                name: components["parameters"]["RouteName"];
            };
            cookie?: never;
        };
        /** Get metrics for one route */
        get: operations["getRouteMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List transports
         * @description Returns the built-in transport
         *     `{"name":"direct","type":"direct","url":""}` first, followed by
         *     configured transports in configuration order.
         */
        get: operations["listTransports"];
        put?: never;
        /**
         * Create a transport
         * @description Adds a transport and hot-applies the configuration. A duplicate name
         *     (including the reserved name `direct`) yields
         *     `400 validation_failed`.
         */
        post: operations["createTransport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transports/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Transport name (`direct` addresses the built-in transport). */
                name: components["parameters"]["TransportName"];
            };
            cookie?: never;
        };
        /**
         * Get a transport
         * @description The built-in `direct` transport is readable like any other.
         */
        get: operations["getTransport"];
        /**
         * Update a transport
         * @description Replaces the named transport and hot-applies the configuration.
         *     `transport.name` must equal the `{name}` path segment, otherwise
         *     `400 validation_failed`. The built-in `direct` transport cannot be
         *     updated (`403 builtin_transport`).
         */
        put: operations["updateTransport"];
        post?: never;
        /**
         * Delete a transport
         * @description Removes the named transport and hot-applies the configuration. The
         *     built-in `direct` transport cannot be deleted
         *     (`403 builtin_transport`). A transport still referenced by one or
         *     more routes cannot be deleted (`409 transport_in_use`, with `detail`
         *     listing the referencing routes).
         */
        delete: operations["deleteTransport"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the global metrics snapshot
         * @description In-memory counters since process start (reset on restart), including
         *     per-route breakdowns and the access-log drop counter.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recent access-log entries
         * @description Returns entries from the in-memory ring buffer, newest first.
         *     Entries never contain query strings, bodies or header values.
         */
        get: operations["getLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test a route end-to-end
         * @description Executes the real pipeline (rewrite → transport → target) for the
         *     named route with a 15-second overall timeout, no redirect following,
         *     and at most 64 KiB of response body read and discarded. Upstream
         *     401/403/404 still report `ok: true` (the link works). Bodies and
         *     authentication headers are never stored or logged.
         */
        post: operations["testRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/transport": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test a transport against a URL
         * @description Sends a probe request to the given URL through the named transport
         *     with a 15-second overall timeout, no redirect following, and at most
         *     64 KiB of response body read and discarded. The URL must be absolute
         *     http/https, otherwise `400 invalid_request`. The test URL and
         *     response body are never stored or logged.
         */
        post: operations["testTransport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Go duration string, e.g. "10s", "1m30s". Serialized as a string in both YAML and JSON.
         * @example 10s
         */
        Duration: string;
        /** @description Root configuration object. The YAML file is the single source of truth. */
        Config: {
            /**
             * @description Configuration schema version. Only `1` is supported.
             * @enum {integer}
             */
            version: 1;
            server?: components["schemas"]["ServerConfig"];
            runtime?: components["schemas"]["RuntimeConfig"];
            network?: components["schemas"]["NetworkConfig"];
            transports?: components["schemas"]["TransportConfig"][];
            routes?: components["schemas"]["RouteConfig"][];
        };
        /** @description Listener configuration for the proxy and admin planes. */
        ServerConfig: {
            proxy?: components["schemas"]["ProxyServerConfig"];
            admin?: components["schemas"]["AdminServerConfig"];
            web?: components["schemas"]["WebConfig"];
        };
        /** @description Data-plane listener. */
        ProxyServerConfig: {
            /**
             * @description Proxy listen address.
             * @default :8080
             * @example :8080
             */
            listen: string;
            tls?: components["schemas"]["TLSConfig"];
        };
        /** @description Optional TLS for the proxy listener (certificates are loaded at startup). */
        TLSConfig: {
            /** @default false */
            enabled: boolean;
            /** @description Path to the certificate chain PEM. Required when `enabled` is true. */
            cert_file?: string;
            /** @description Path to the private key PEM. Required when `enabled` is true. */
            key_file?: string;
        };
        /** @description Admin API / WebUI listener. */
        AdminServerConfig: {
            /**
             * @description Defaults to true when omitted.
             * @default true
             */
            enabled: boolean | null;
            /**
             * @description Admin listen address. Defaults to loopback.
             * @default 127.0.0.1:9090
             * @example 127.0.0.1:9090
             */
            listen: string;
        };
        /** @description Embedded WebUI toggle. The WebUI requires the admin server. */
        WebConfig: {
            /**
             * @description Defaults to true when omitted; forced off when the admin server is disabled.
             * @default true
             */
            enabled: boolean | null;
        };
        /** @description Runtime tuning. */
        RuntimeConfig: {
            /**
             * @default info
             * @enum {string}
             */
            log_level: "debug" | "info" | "warn" | "error";
            /**
             * @description Capacity of the in-memory access-log ring buffer. `0` disables it. Defaults to 1000 when omitted.
             * @default 1000
             */
            recent_logs: number | null;
        };
        /** @description Global outbound tuning. No overall request deadline exists so long-lived SSE streams are never cut off. */
        NetworkConfig: {
            /** @description Dial timeout. Defaults to "10s". */
            dial_timeout?: components["schemas"]["Duration"];
            /** @description TLS handshake timeout. Defaults to "10s". */
            tls_handshake_timeout?: components["schemas"]["Duration"];
            /** @description Time allowed for upstream response headers. Defaults to "120s". */
            response_header_timeout?: components["schemas"]["Duration"];
            /** @description Idle pooled-connection timeout. Defaults to "90s". */
            idle_connection_timeout?: components["schemas"]["Duration"];
        };
        /** @description One prefix → target mapping. */
        RouteConfig: {
            /**
             * @description Unique route name.
             * @example openai
             */
            name: string;
            /**
             * @description Defaults to true when omitted.
             * @default true
             */
            enabled: boolean | null;
            /**
             * @description Request path prefix. Must start with "/"; a non-root prefix must not end with "/"; must not contain "?", "#", ".." or "//" segments. "/" matches everything.
             * @example /openai
             */
            prefix: string;
            /**
             * @description Absolute http/https target URL without userinfo, query or fragment.
             * @example https://api.openai.com/v1
             */
            target: string;
            /**
             * @description Remove proxy metadata request headers (Forwarded, Via, X-Forwarded-For, X-Forwarded-Host, X-Forwarded-Proto) before forwarding, so the target never sees them. Set to false to pass inbound values through unchanged. PipeRouter never adds these headers either way. Defaults to true when omitted.
             * @default true
             */
            strip_forward_headers: boolean | null;
            /**
             * @description Remove the matched prefix before joining with the target base path. Defaults to true when omitted.
             * @default true
             */
            strip_prefix: boolean | null;
            /**
             * @description Name of the transport to use. Defaults to the built-in "direct" when omitted.
             * @default direct
             * @example jp-proxy
             */
            transport: string;
        };
        /** @description An outbound link. Configured transports are of type "http" or "socks5"; type "direct" only appears on the synthetic built-in entry returned by the API and cannot be declared in the configuration. */
        TransportConfig: {
            /**
             * @description Unique transport name. "direct" is reserved for the built-in transport.
             * @example jp-proxy
             */
            name: string;
            /**
             * @example http
             * @enum {string}
             */
            type: "direct" | "http" | "socks5";
            /**
             * @description Proxy server URL without userinfo. Scheme must be "http" for type http and "socks5" for type socks5. Empty for the built-in direct transport.
             * @example http://127.0.0.1:7890
             */
            url: string;
        };
        /** @description Process and configuration status. */
        StatusResponse: {
            /**
             * @description PipeRouter build version.
             * @example 0.1.0
             */
            version: string;
            /** Format: date-time */
            started_at: string;
            /** Format: double */
            uptime_seconds: number;
            proxy: {
                /** @example :8080 */
                listen: string;
                tls_enabled: boolean;
            };
            admin: {
                /** @example 127.0.0.1:9090 */
                listen: string;
            };
            config: {
                /** @description False when the last reload attempt failed (the previous valid configuration keeps serving). */
                valid: boolean;
                /** @description Error from the last failed reload; empty when valid. */
                last_error: string;
                /**
                 * @description Revision of the ACTIVE snapshot.
                 * @example sha256:9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
                 */
                revision: string;
                /** Format: date-time */
                loaded_at: string;
                /**
                 * @description Configuration file path.
                 * @example piperouter.yaml
                 */
                path: string;
            };
        };
        /** @description Full normalized configuration together with its revision. */
        ConfigEnvelope: {
            /**
             * @description "sha256:" + hex(sha256(canonical YAML)) of the configuration.
             * @example sha256:9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
             */
            revision: string;
            config: components["schemas"]["Config"];
        };
        /** @description Full-configuration replacement request. */
        ConfigUpdateRequest: {
            /** @description Expected active revision; omit or leave empty to skip the conflict check. */
            revision?: string;
            config: components["schemas"]["Config"];
        };
        ValidateRequest: {
            config: components["schemas"]["Config"];
        };
        ValidateResponse: {
            valid: boolean;
            /** @description Every validation problem found; empty when valid. */
            issues: string[];
        };
        RouteListResponse: {
            /** @description Routes in configuration order. */
            routes: components["schemas"]["RouteConfig"][];
        };
        /** @description Route create/update request. */
        RouteUpsertRequest: {
            /** @description Expected active revision; omit or leave empty to skip the conflict check. */
            revision?: string;
            route: components["schemas"]["RouteConfig"];
        };
        /** @description Result of a route mutation. */
        RouteEnvelope: {
            /** @description New active configuration revision. */
            revision: string;
            route: components["schemas"]["RouteConfig"];
        };
        TransportListResponse: {
            /** @description The synthetic built-in entry `{"name":"direct","type":"direct","url":""}` first, then configured transports in configuration order. */
            transports: components["schemas"]["TransportConfig"][];
        };
        /** @description Transport create/update request. */
        TransportUpsertRequest: {
            /** @description Expected active revision; omit or leave empty to skip the conflict check. */
            revision?: string;
            transport: components["schemas"]["TransportConfig"];
        };
        /** @description Result of a transport mutation. */
        TransportEnvelope: {
            /** @description New active configuration revision. */
            revision: string;
            transport: components["schemas"]["TransportConfig"];
        };
        /** @description Latency distribution summary derived from a fixed-bucket histogram. */
        LatencySummary: {
            /** Format: int64 */
            count: number;
            /** Format: double */
            p50_ms: number;
            /** Format: double */
            p95_ms: number;
            /** Format: double */
            p99_ms: number;
        };
        /** @description Per-route counters. Reset on process restart. */
        RouteMetrics: {
            name: string;
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            status_2xx: number;
            /** Format: int64 */
            status_3xx: number;
            /** Format: int64 */
            status_4xx: number;
            /** Format: int64 */
            status_5xx: number;
            /** Format: int64 */
            upstream_errors: number;
            /** Format: int64 */
            active: number;
            latency: components["schemas"]["LatencySummary"];
            /**
             * Format: date-time
             * @description Null if the route has never served a request.
             */
            last_request_at: string | null;
        };
        /** @description Global metrics snapshot merged with the access-log drop counter. In-memory only; reset on process restart. */
        MetricsSnapshot: {
            /** Format: date-time */
            started_at: string;
            /** Format: double */
            uptime_seconds: number;
            /** Format: int64 */
            total_requests: number;
            /**
             * Format: int64
             * @description 5xx responses plus upstream errors.
             */
            error_requests: number;
            /** Format: int64 */
            active_requests: number;
            /** Format: int64 */
            active_websockets: number;
            /** Format: int64 */
            active_sse: number;
            route_count: number;
            transport_count: number;
            latency: components["schemas"]["LatencySummary"];
            /** @description Per-route metrics, sorted by name. */
            routes: components["schemas"]["RouteMetrics"][];
            /**
             * Format: int64
             * @description Access-log entries dropped by the ring buffer due to overflow.
             */
            log_dropped: number;
        };
        /** @description One access-log record. Never contains query strings, bodies or header values — except the client's forward headers (see forward_headers), which are proxy metadata, not credentials. */
        AccessLogEntry: {
            /** Format: date-time */
            time: string;
            /** @description Matched route name; empty if the request matched no route. */
            route: string;
            /** @example GET */
            method: string;
            /**
             * @description Request path WITHOUT the query string.
             * @example /openai/models
             */
            path: string;
            /** @example 200 */
            status: number;
            /** Format: double */
            duration_ms: number;
            transport: string;
            /** @enum {string} */
            streaming: "" | "sse" | "websocket";
            /** @description Error classification code (e.g. `upstream_timeout`); empty if none. */
            error: string;
            /** @description Proxy-metadata headers the client sent (Forwarded, Via, X-Forwarded-For, X-Forwarded-Host, X-Forwarded-Proto), in stable order — recorded even when strip_forward_headers removes them from the forwarded request. Only headers actually present are listed; values are truncated to 256 characters. Omitted when the client sent none. */
            forward_headers?: {
                /** @example X-Forwarded-For */
                name: string;
                /** @example 203.0.113.7 */
                value: string;
            }[];
        };
        LogsResponse: {
            /** @description Matching entries, newest first. */
            entries: components["schemas"]["AccessLogEntry"][];
            /**
             * Format: int64
             * @description Total entries dropped due to ring-buffer overflow.
             */
            dropped: number;
            /** @description Current ring-buffer capacity (0 = disabled). */
            capacity: number;
        };
        /** @description Route diagnostics request. */
        RouteTestRequest: {
            /**
             * @description Name of the route to test.
             * @example openai
             */
            route: string;
            /**
             * @description Extra path appended below the route prefix before rewriting.
             * @example /models
             */
            path?: string;
            /**
             * @description HTTP method for the probe.
             * @default GET
             */
            method: string;
        };
        /** @description Transport diagnostics request. */
        TransportTestRequest: {
            /**
             * @description Name of the transport to test ("direct" is allowed).
             * @example jp-proxy
             */
            transport: string;
            /**
             * @description Absolute http/https URL to probe.
             * @example https://api.openai.com/v1/models
             */
            url: string;
            /**
             * @description HTTP method for the probe.
             * @default GET
             */
            method: string;
        };
        /** @description Outcome of a diagnostics probe. Upstream 401/403/404 responses still report `ok: true` — the network link works. */
        DiagnosticsResult: {
            ok: boolean;
            /**
             * @description Final rewritten target URL that was probed.
             * @example https://api.openai.com/v1/models
             */
            target_url: string;
            /** @description Transport used for the probe. */
            transport: string;
            /** @description Upstream HTTP status; 0 if no HTTP response was received. */
            status: number;
            /**
             * @description Stage at which the probe failed; empty on success.
             * @enum {string}
             */
            error_stage: "" | "resolve" | "connect" | "tls" | "response";
            /** @description Sanitized error message; empty on success. */
            error: string;
            /**
             * Format: double
             * @description Time until upstream response headers were received.
             */
            header_duration_ms: number;
            /** Format: double */
            total_duration_ms: number;
        };
        /** @description Standard error envelope. */
        ApiError: {
            /**
             * @description Machine-readable error code.
             * @enum {string}
             */
            error: "validation_failed" | "revision_conflict" | "not_found" | "builtin_transport" | "transport_in_use" | "origin_not_allowed" | "invalid_request" | "method_not_allowed" | "internal_error";
            /** @description Optional human-readable detail (never contains credentials or proxy URLs). */
            detail?: string;
            /** @description Present only for `validation_failed` — one entry per validation problem. */
            issues?: string[];
        };
    };
    responses: {
        /** @description `validation_failed` — the resulting configuration is invalid; the `issues` array lists every problem. Malformed JSON or an unprocessable body yields `invalid_request` instead. */
        BadRequestValidation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description `invalid_request` — malformed JSON or an unacceptable field value. */
        BadRequestInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description `origin_not_allowed` — the request carried an `Origin` header whose host does not match the request `Host`. */
        OriginNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description `not_found` — no object with the given name exists. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description `revision_conflict` — the supplied revision does not match the active configuration revision; reload and retry. */
        RevisionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description Route name. */
        RouteName: string;
        /** @description Transport name (`direct` addresses the built-in transport). */
        TransportName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active configuration and its revision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEnvelope"];
                };
            };
        };
    };
    putConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Configuration applied; new revision returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEnvelope"];
                };
            };
            400: components["responses"]["BadRequestValidation"];
            403: components["responses"]["OriginNotAllowed"];
            409: components["responses"]["RevisionConflict"];
        };
    };
    validateConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Validation outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            400: components["responses"]["BadRequestInvalid"];
            403: components["responses"]["OriginNotAllowed"];
        };
    };
    listRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteListResponse"];
                };
            };
        };
    };
    createRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteUpsertRequest"];
            };
        };
        responses: {
            /** @description Route created; new configuration revision returned. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteEnvelope"];
                };
            };
            400: components["responses"]["BadRequestValidation"];
            403: components["responses"]["OriginNotAllowed"];
            409: components["responses"]["RevisionConflict"];
        };
    };
    getRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route name. */
                name: components["parameters"]["RouteName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The route. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteConfig"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route name. */
                name: components["parameters"]["RouteName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteUpsertRequest"];
            };
        };
        responses: {
            /** @description Route updated; new configuration revision returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteEnvelope"];
                };
            };
            400: components["responses"]["BadRequestValidation"];
            403: components["responses"]["OriginNotAllowed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["RevisionConflict"];
        };
    };
    deleteRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route name. */
                name: components["parameters"]["RouteName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["OriginNotAllowed"];
            404: components["responses"]["NotFound"];
        };
    };
    getRouteMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route name. */
                name: components["parameters"]["RouteName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics for the named route. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteMetrics"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listTransports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transport list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportListResponse"];
                };
            };
        };
    };
    createTransport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransportUpsertRequest"];
            };
        };
        responses: {
            /** @description Transport created; new configuration revision returned. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportEnvelope"];
                };
            };
            400: components["responses"]["BadRequestValidation"];
            403: components["responses"]["OriginNotAllowed"];
            409: components["responses"]["RevisionConflict"];
        };
    };
    getTransport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Transport name (`direct` addresses the built-in transport). */
                name: components["parameters"]["TransportName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The transport. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportConfig"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateTransport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Transport name (`direct` addresses the built-in transport). */
                name: components["parameters"]["TransportName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransportUpsertRequest"];
            };
        };
        responses: {
            /** @description Transport updated; new configuration revision returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportEnvelope"];
                };
            };
            400: components["responses"]["BadRequestValidation"];
            /** @description `builtin_transport` when `{name}` is `direct`, or `origin_not_allowed` when the Origin check fails. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["RevisionConflict"];
        };
    };
    deleteTransport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Transport name (`direct` addresses the built-in transport). */
                name: components["parameters"]["TransportName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transport deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `builtin_transport` when `{name}` is `direct`, or `origin_not_allowed` when the Origin check fails. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description `transport_in_use` — the transport is still referenced by one or more routes; `detail` lists the referencing route names. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current metrics snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsSnapshot"];
                };
            };
        };
    };
    getLogs: {
        parameters: {
            query?: {
                /** @description Maximum number of entries to return. Omitted or non-positive values return all buffered entries. */
                limit?: number;
                /** @description Exact route name to filter by. */
                route?: string;
                /** @description Status-class filter: `2xx`–`5xx` match the response status family; `error` matches entries whose error classification is non-empty. */
                status_class?: "2xx" | "3xx" | "4xx" | "5xx" | "error";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered log entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsResponse"];
                };
            };
        };
    };
    testRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteTestRequest"];
            };
        };
        responses: {
            /** @description Test result (also returned when the probe itself failed; see `ok`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsResult"];
                };
            };
            400: components["responses"]["BadRequestInvalid"];
            403: components["responses"]["OriginNotAllowed"];
            404: components["responses"]["NotFound"];
        };
    };
    testTransport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransportTestRequest"];
            };
        };
        responses: {
            /** @description Test result (also returned when the probe itself failed; see `ok`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsResult"];
                };
            };
            400: components["responses"]["BadRequestInvalid"];
            403: components["responses"]["OriginNotAllowed"];
            404: components["responses"]["NotFound"];
        };
    };
}
